package sm2

import (
	"crypto/ecdsa"
	"crypto/rand"
	"errors"
	"io"
	"math/big"
	"time"

	"github.com/emmansun/gmsm/pkcs"
	gmsmPkcs7 "github.com/emmansun/gmsm/pkcs7"
	smx509 "github.com/emmansun/gmsm/smx509"
	"github.com/iuboy/pollux-go/internal/memsecure"
	"github.com/iuboy/pollux-go/sm4"
)

// errDecryptFailed is the single opaque error returned by every envelope
// decryption failure (bad PKCS#7 structure, bad recipient cert, SM2 key
// mismatch, symmetric decryption failure). Returning one constant message —
// instead of distinct underlying errors — denies an attacker any oracle for
// distinguishing which envelope layer failed, which matters when the inner
// symmetric mode is unauthenticated (e.g. CBC). Shared by EnvelopeDecrypt and
// EnvelopeDecryptSM4 so both decryption paths present an identical failure
// surface; callers can also match it with errors.Is.
var errDecryptFailed = errors.New("sm2: decryption failed")

// EnvelopeResult represents a digital envelope encryption result.
type EnvelopeResult struct {
	// DER-encoded PKCS#7 EnvelopedData (contains SM2-encrypted SM4 key + SM4 ciphertext).
	EnvelopedData []byte
	// Temporary certificate DER, needed for RecipientInfo matching during decryption.
	certDER []byte
}

// EnvelopeEncrypt encrypts plaintext using SM2 public key digital envelope.
// Internal process: generate random SM4 key -> SM4-CBC encrypt plaintext -> SM2 encrypt SM4 key -> assemble PKCS#7 EnvelopedData.
func EnvelopeEncrypt(pub *ecdsa.PublicKey, plaintext []byte) (*EnvelopeResult, error) {
	if pub == nil {
		return nil, errors.New("sm2: nil public key")
	}

	cert, certDER, err := createTempCertForEnvelope()
	if err != nil {
		return nil, err
	}

	ed, err := gmsmPkcs7.NewSM2EnvelopedData(pkcs.SM4, plaintext)
	if err != nil {
		return nil, err
	}

	if err := ed.AddRecipient(cert, 0, func(c *smx509.Certificate, key []byte) ([]byte, error) {
		return EncryptASN1(rand.Reader, pub, key)
	}); err != nil {
		return nil, err
	}

	der, err := ed.Finish()
	if err != nil {
		return nil, err
	}

	return &EnvelopeResult{EnvelopedData: der, certDER: certDER}, nil
}

// EnvelopeDecrypt decrypts digital envelope using SM2 private key.
//
// SECURITY NOTE: The decryption-failure path (p7.Decrypt) returns a single
// generic "sm2: decryption failed" error instead of the underlying PKCS#7
// error. This matches EnvelopeDecryptSM4's hardening: a digital envelope has
// two layers (SM2 key-unwrapping + symmetric decryption), and a distinguishable
// ERROR MESSAGE is the necessary precondition of a decryption oracle (classic
// padding-oracle shape); unifying the messages closes that surface. Residual
// timing differences between the layers still exist and are accepted —
// exploiting them requires high-precision measurement typically masked by
// network jitter. Input-validation failures (nil args, missing certificate)
// are still reported verbatim since they are caller errors, not adversarial
// decryption outcomes.
func EnvelopeDecrypt(priv *PrivateKey, env *EnvelopeResult) ([]byte, error) {
	if priv == nil || env == nil {
		return nil, errors.New("sm2: nil private key or envelope")
	}
	if len(env.certDER) == 0 {
		return nil, errors.New("sm2: missing certificate in envelope")
	}

	p7, err := gmsmPkcs7.Parse(env.EnvelopedData)
	if err != nil {
		return nil, errDecryptFailed
	}
	cert, err := smx509.ParseCertificate(env.certDER)
	if err != nil {
		// certDER is part of the envelope; a parse failure here is a malformed
		// envelope rather than a caller input error, so treat it as a decrypt
		// failure (opaque) for consistency with the anti-oracle posture above.
		return nil, errDecryptFailed
	}

	plaintext, err := p7.Decrypt(cert, priv)
	if err != nil {
		return nil, errDecryptFailed
	}
	return plaintext, nil
}

// EnvelopeEncryptSM4 encrypts using SM2+SM4-GCM digital envelope (simplified, non-PKCS#7 format).
// Returns SM2-encrypted SM4 key, GCM nonce, SM4-GCM ciphertext.
func EnvelopeEncryptSM4(pub *ecdsa.PublicKey, plaintext []byte) (encryptedKey, nonce, ciphertext []byte, err error) {
	if pub == nil {
		return nil, nil, nil, errors.New("sm2: nil public key")
	}

	// Generate random SM4 key
	sm4Key, err := sm4.GenerateKey()
	if err != nil {
		return nil, nil, nil, err
	}
	defer memsecure.ZeroBytes(sm4Key)

	// SM2-encrypt the SM4 key
	encryptedKey, err = EncryptASN1(rand.Reader, pub, sm4Key)
	if err != nil {
		return nil, nil, nil, err
	}

	// SM4-GCM encrypt plaintext
	aead, err := sm4.NewGCM(sm4Key)
	if err != nil {
		return nil, nil, nil, err
	}

	nonce = make([]byte, aead.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, nil, nil, err
	}

	// #nosec G407 -- nonce is CSPRNG-generated by rand.Read above, not a hardcoded constant.
	ciphertext = aead.Seal(nil, nonce, plaintext, nil)
	return
}

// EnvelopeDecryptSM4 decrypts SM2+SM4-GCM digital envelope (simplified).
//
// SECURITY NOTE: Error messages are intentionally generic ("sm2: decryption failed")
// to prevent timing side-channel leakage. An attacker who can measure decryption time
// should not be able to distinguish between "SM2 decryption failed" and
// "SM4-GCM authentication failed" errors.
func EnvelopeDecryptSM4(priv *PrivateKey, encryptedKey, nonce, ciphertext []byte) ([]byte, error) {
	if priv == nil {
		return nil, errors.New("sm2: nil private key")
	}

	// SM2-decrypt the SM4 key
	sm4Key, err := Decrypt(priv, encryptedKey)
	if err != nil {
		return nil, errDecryptFailed
	}
	defer memsecure.ZeroBytes(sm4Key)

	// SM4-GCM decrypt
	aead, err := sm4.NewGCM(sm4Key)
	if err != nil {
		return nil, errDecryptFailed
	}

	plaintext, err := aead.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, errDecryptFailed
	}

	return plaintext, nil
}

// createTempCertForEnvelope creates a temporary self-signed certificate for PKCS#7 envelope operations.
// Returns parsed certificate and raw DER (for RecipientInfo matching during subsequent decryption).
func createTempCertForEnvelope() (*smx509.Certificate, []byte, error) {
	tmpPriv, err := GenerateKey(rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	// The temporary private key is only needed to self-sign the throwaway
	// recipient certificate; it is never used to decrypt anything. Zero its
	// scalar value immediately after signing per the minimal-exposure principle
	// in docs/security/memory-management.md.
	//
	// NOTE: math/big.Int does not expose its internal nat words, so a fully
	// secure overwrite of the backing array is impossible from outside the
	// type. The previous FillBytes-into-scratch + zero-scratch pattern only
	// cleared a COPY of the scalar (FillBytes is a read), leaving the real key
	// intact — a silent no-op. SetInt64(0) at least zeroes the logical scalar
	// value so the key is no longer usable or directly readable. This matches
	// jwt.sm2SignerVerifier.Zeroize and is the best-effort convention Go's own
	// crypto/ecdsa documents for big.Int-backed keys.
	defer func() {
		if tmpPriv != nil && tmpPriv.D != nil {
			tmpPriv.D.SetInt64(0)
		}
	}()

	sn, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, err
	}

	tmpl := &smx509.Certificate{
		SerialNumber:          sn,
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(24 * time.Hour),
		KeyUsage:              smx509.KeyUsageKeyEncipherment | smx509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
	}

	der, err := smx509.CreateCertificate(rand.Reader, tmpl, tmpl, &tmpPriv.PublicKey, tmpPriv)
	if err != nil {
		return nil, nil, err
	}

	cert, err := smx509.ParseCertificate(der)
	if err != nil {
		return nil, nil, err
	}
	return cert, der, nil
}
